name: GitHub Actions Demo
on: [push]
jobs:
  build-check-zephyr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install --no-install-recommends ninja-build gperf \
          ccache dfu-util gcc-multilib g++-multilib libsdl2-dev
      - name: Verify Versions
        run: |
          cmake --version
          python3 --version
      - name: Install West
        run: |
          pip3 install --user -U west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Get Zephyr Source Code and Export Zephyr CMake
        run: |
          west init ~/zephyrproject
          cd ~/zephyrproject
          west update
          west zephyr-export
      - name: Install requirements.txt
        run: pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt
      - name: Install Zephyr SDK
        run: |
          cd ~
          ls
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.12.4/zephyr-sdk-0.12.4-x86_64-linux-setup.run
          chmod +x zephyr-sdk-0.12.4-x86_64-linux-setup.run
          ./zephyr-sdk-0.12.4-x86_64-linux-setup.run -- -d ~/zephyr-sdk-0.12.4
      - name: Install Espressif and Env Variables
        run: |
          cd ~/zephyrproject
          west espressif install
          echo "ZEPHYR_TOOLCHAIN_VARIANT=espressif" >> $GITHUB_ENV
          echo "ESPRESSIF_TOOLCHAIN_PATH=$HOME/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf" >> $GITHUB_ENV
          echo "$ESPRESSIF_TOOLCHAIN_PATH/bin" >> $GITHUB_PATH
          west update
          west espressif update
      - name: Build Hello World
        run: |
          cd ~/zephyrproject/zephyr
          west build -b esp32 samples/hello_world
      - name: MQTT Demos
        run: |
          cd ~/zephyrproject
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/mqtt/mqtt_plaintext --pristine -- -DCMAKE_C_FLAGS=" -DBROKER_ENDPOINT=\\\"broker_endpoint\\\" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/mqtt/mqtt_basic_tls --pristine -- -DCMAKE_C_FLAGS=" -DBROKER_ENDPOINT=\\\"broker_endpoint\\\" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/mqtt/mqtt_mutual_auth --pristine -- -DCMAKE_C_FLAGS=" -DAWS_IOT_ENDPOINT=\\\"aws_iot_endpoint\\\" -DCLIENT_CERT_PEM=\\\"client_certificate\\\" -DCLIENT_PRIVATE_KEY_PEM=\\\"client_private_key\\\" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "
      - name: HTTP Demos
        run: |
          cd ~/zephyrproject
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/http/http_plaintext --pristine -- -DCMAKE_C_FLAGS=" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/http/http_mutual_auth --pristine -- -DCMAKE_C_FLAGS=" -DAWS_IOT_ENDPOINT=\\\"aws_iot_endpoint\\\" -DCLIENT_CERT_PEM=\\\"client_certificate\\\" -DCLIENT_PRIVATE_KEY_PEM=\\\"client_private_key\\\" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "
      - name: Shadow Demos
        run: |
          cd ~/zephyrproject
          west build -b esp32 ~/work/aws-iot-device-embedded-c-sdk-for-zephyr/aws-iot-device-embedded-c-sdk-for-zephyr/demos/shadow/shadow_main --pristine -- -DCMAKE_C_FLAGS=" -DAWS_IOT_ENDPOINT=\\\"aws_iot_endpoint\\\" -DCLIENT_CERT_PEM=\\\"client_certificate\\\" -DCLIENT_PRIVATE_KEY_PEM=\\\"client_private_key\\\" -DWIFI_NETWORK_SSID=\\\"wifi\\\" -DWIFI_NETWORK_PASSWORD=\\\"password\\\" "